package com.ftn.sbnz.rules.forward;

import com.ftn.sbnz.model.models.Action;
import com.ftn.sbnz.model.models.Culture;
global java.time.LocalDate currentDate;

rule "Krompir - Navodnjavanje"
when
    $c : Culture(name == "Krompir", state == 0)
    $a : Action(name == "Navodnjavanje", culture == $c)
then
    if ($a.getDateDone() != null && !$a.getDateDone().isAfter($a.getDeadline())) {
        $c.setState(1);
        System.out.println("Krompir: Navodnjavanje obavljeno na vreme. Novi nivo: " + $c.getState());
    }
    update($c);
end

rule "Krompir - Đubrenje"
when
    $c : Culture(name == "Krompir", state == 1)
    $a : Action(name == "Đubrenje", culture == $c)
then
    if ($a.getDateDone() != null && !$a.getDateDone().isAfter($a.getDeadline())) {
        $c.setState(2);
        System.out.println("Krompir: Đubrenje obavljeno na vreme. Novi nivo: " + $c.getState());
    }
    update($c);
end

rule "Krompir - Zagrtanje"
when
    $c : Culture(name == "Krompir", state == 2)
    $a : Action(name == "Zagrtanje", culture == $c)
then
    if ($a.getDateDone() != null && !$a.getDateDone().isAfter($a.getDeadline())) {
        $c.setState(3);
        System.out.println("Krompir: Zagrtanje obavljeno na vreme. Novi nivo: " + $c.getState());
    }
    update($c);
end
