package com.ftn.sbnz.model;

public enum ProblemName {
    DOWNY_MILDEW,
    ONION_FLY,
    BEAN_LEAF_SPOT,
    APHIDS,
    TOMATO_BLIGHT,
    POTATO_BLIGHT,
    COLORADO_POTATO_BEETLE,
    POWDERY_MILDEW,
    CORN_MOLD,
    CORN_BORER,
    DRY_BRANCHES,
    MONILIA,
    BARK_CRACKING,
    APPLE_SCAB,
    CODLING_MOTH,
    FRUIT_ROT,
    SHOT_HOLE_DISEASE,
    PLUM_SAWFLY,
    GRAPE_POWDERY_MILDEW,
    GRAPE_MOTH
}