package com.ftn.sbnz.model;

public enum SolutionName {
    APPLY_FUNGICIDE,
    APPLY_INSECTICIDE,
    APPLY_FERTILIZATION,
    REMOVE_INFECTED_LEAVES,
    REMOVE_INFECTED_FRUITS,
    PRUNE_INFECTED_BRANCHES,
    ADD_PROTECTION
}