package garden_cep;

import com.ftn.sbnz.model.WeatherDayInfo;
import com.ftn.sbnz.model.CultureName;

rule "Grape: critical time detected"
    when
        $avgTemp: Number() from accumulate(
            $w: WeatherDayInfo() over window:time(7d),
            average($w.getTemperature())
        )
        $avgRain: Number() from accumulate(
            $w: WeatherDayInfo() over window:time(7d),
            average($w.getRainfall())
        )
        $count: Number() from accumulate(
            $w: WeatherDayInfo() over window:time(7d),
            count($w)
        )
        eval( $count.intValue() >= 7 )
        eval( $avgTemp.doubleValue() >= cultureThresholdProvider.getOptimalTemperature(CultureName.GRAPE) * 1.5 )
        eval( $avgRain.doubleValue() < cultureThresholdProvider.getOptimalWeeklyRainfall(CultureName.GRAPE) / 7 * 0.75 )
    then
        criticalPeriodUpdater.updateCulture(CultureName.GRAPE, true, currentDate);
end

rule "Grape: critical time ended"
    when
        $avgTemp: Number() from accumulate(
            $w: WeatherDayInfo() over window:time(7d),
            average($w.getTemperature())
        )
        $avgRain: Number() from accumulate(
            $w: WeatherDayInfo() over window:time(7d),
            average($w.getRainfall())
        )
        $count: Number() from accumulate(
            $w: WeatherDayInfo() over window:time(7d),
            count($w)
        )
        eval( !( $count.intValue() >= 7
                 && $avgTemp.doubleValue() >= cultureThresholdProvider.getOptimalTemperature(CultureName.GRAPE) * 1.5
                 && $avgRain.doubleValue() < cultureThresholdProvider.getOptimalWeeklyRainfall(CultureName.GRAPE) / 7 * 0.75 ) )
    then
        criticalPeriodUpdater.updateCulture(CultureName.GRAPE, false, currentDate);
end